### ISSUE TITLE
Dark mode woks not as expected

### ISSUE THREAD

**Issue by AstRonin** [agusmakmun/django-markdown-editor#204]
Dark mode woks not as expected

## Details
- OS (Operating System) version: Mac (13.3.1 (a))
- Browser and browser version: Chrome (Version 113.0.5672.63 (Official Build) (arm64))
- Django version: Django = "^4.1.7"
- Martor version & theme: martor = "^1.6.20" (bootstrap)

### Steps to reproduce

- Set mode to Dark in System Settings

![image](https://github.com/agusmakmun/django-markdown-editor/assets/2378239/e6bba7b0-c698-4c45-ae41-25716670bb84)

Could we also remove  `@media (prefers-color-scheme: dark)` and make depends on Django mode, not a System?

**Comment by grahame** [comment]
I'm seeing this too, but only for body text in Markdown; headings work fine.

**Comment by Sispheor** [comment]
Seems that title level 1 and 2 need more contrast too
![image](https://github.com/agusmakmun/django-markdown-editor/assets/2573405/755ebb48-e286-4ffe-b804-59226cafe25f)

**Comment by wkt84** [comment]
Hello,

I want to reopen this issue because the display problem with the editor's preview in Django's dark mode persists. The issue was previously marked as resolved and closed, but the problem seems to remain. I suspect there might be an issue with the martor-bootstrap.css, specifically with div.martor-preview, which may not be fully compatible with dark mode, but I am not entirely sure.

Here are the details of my setup:

- OS version: Windows 10 Pro
- Browser and version: Chrome 124.0.6367.91 (Official Build)
- Django version: 4.2.11
- Martor version: 1.6.44
- Markdown version: 3.1.1

I have attached screenshots showing the editor, the preview, and the selected preview when using dark mode, which highlight the issue.
![martor_editor](https://github.com/agusmakmun/django-markdown-editor/assets/5171897/d6ac3325-bc27-4473-835d-e1bc01836e30)
![martor_preview1](https://github.com/agusmakmun/django-markdown-editor/assets/5171897/0fa2bf59-03aa-4ea2-9f94-8483029033e1)
![martor_preview2](https://github.com/agusmakmun/django-markdown-editor/assets/5171897/961e280b-190e-401e-8003-7b397d894285)


Your assistance in resolving this would be greatly appreciated.

Thank you.
