### ISSUE TITLE
HTML Code getting removed.

### ISSUE THREAD

**Issue by astikanand** [agusmakmun/django-markdown-editor#25]
Whenever any HTML Code is written inside the editor it is being removed as `[HTML_REMOVED]`.
Ideally, this should not happen. Can you please have a look into it.

**Comment by agusmakmun** [comment]
Because we using safe mode for default configuration:

```
MARTOR_MARKDOWN_SAFE_MODE = True
```

> This case especially to handle xss injection, looks like `<script>location.reload();</script>` or etc.

But, you can also see what [docs says](https://python-markdown.github.io/reference/#safe_mode):
- `False` - Raw HTML is passed through unaltered.
- `"replace"` - Replace all HTML blocks with the text assigned to html_replacement_text
- `"remove"` - All raw HTML will be completely stripped from the text with no warning to the author.
- `"escape"` - All raw HTML will be escaped and included in the document.

**Comment by astikanand** [comment]
Very very thanks for the quick response.

Regards,
Astik Anand

**Comment by jdhurwitz** [comment]
@agusmakmun, When my field contains HTML as shown below, editing MARTOR_MARKDOWN_SAFE_MODE only gives me the html tags (image attached) formatted in with the text. However, I'd like these tags to be used to actually format the field itself. For example, if there is a <br> then there should be a line break and the user should not see any of the tags. With django-markdownx, this is supported. Am I doing something wrong here/what should I check?

`&lt;p&gt;Since strings internally are converted to &lt;code&gt;uint64&lt;/code&gt; for space efficiency on the eos.io blockchain what are the restrictions that need to be followed for:&lt;/p&gt;&#xA;&#xA;&lt;ul&gt;&#xA;&lt;li&gt;actions&lt;/li&gt;&#xA;&lt;li&gt;tables&lt;/li&gt;&#xA;&lt;li&gt;index identifiers (within &lt;code&gt;multi_index&lt;/code&gt;'s)&lt;/li&gt;&#xA;&lt;li&gt;contract names&lt;/li&gt;&#xA;&lt;li&gt;anything else I've forgotten?&lt;/li&gt;&#xA;&lt;/ul&gt;&#xA;`


![image](https://user-images.githubusercontent.com/9702107/43169143-bdfa97aa-8f54-11e8-907d-0ca61178554b.png)

**Comment by agusmakmun** [comment]
@jdhurwitz you should load this templatetags first.

```
{% load martortags %}
{{ field_name|safe_markdown }}

# example
{{ post.description|safe_markdown }}
```

**Comment by jdhurwitz** [comment]
@agusmakmun  Right, I have done that, but my text shown in the first box appears with the tags, whereas I want it to actually parse the tags and display it formatted.

**Comment by jdhurwitz** [comment]
I'm doing exactly that, and I still get it showing all the tags as shown in the bottom of my first comment on this thread. Here is my HTML:

![image](https://user-images.githubusercontent.com/9702107/43175013-dfd94106-8f71-11e8-961f-ed54f52d76f0.png)

**Comment by uditvashisht** [comment]
Hi, is there any way, in which I can add the html too ? e.g. if I want to embed a youtube  video in my article or a tweet? It says <HTML_REMOVED>.

**Comment by agusmakmun** [comment]
@uditvashisht you just need to add the youtube link into editor, don't use `<iframe` or `<embed` syntax.

**Comment by uditvashisht** [comment]
In that case, it's not possible to align that video at the centre. Also what about Twitter threads...
